//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamtasticPublicWebsite.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentPublicSite
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string NavLink { get; set; }
        public string PageText { get; set; }
        public byte[] PageImage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public string PageImageContentType { get; set; }
        public bool IsUniqueServicePage { get; set; }
    }
}
